version: '3.8'

services:
  api:
    build:
      context: apps/api
      dockerfile: Dockerfile.dev
    container_name: pengi-api
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=debug
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./apps/api/.env
    volumes:
      - ./apps/api:/app
    networks:
      - gentoo_network

  db:
    image: postgres:15-alpine
    container_name: pengi-db-dev
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pengi_gentoo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - gentoo_network

  gotenberg:
    container_name: gotenberg-gentoo
    image: gotenberg/gotenberg:8
    restart: on-failure
    ports:
      - "3000:3000"
    networks:
      - gentoo_network

volumes:
  postgres_data:

networks:
  gentoo_network:
    driver: bridge