# Build Stage
FROM golang:1.26.3-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o main cmd/main.go

# Runtime Stage
FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/main .
COPY --from=builder /app/i18n/messages ./i18n/messages
COPY features/clinical/templates ./features/clinical/templates

EXPOSE 8080

CMD ["./main"]
