# Build Stage
FROM golang:1.25-alpine

WORKDIR /app

# Instalar 'air' para hot-reloading
RUN go install github.com/air-verse/air@latest

COPY go.mod go.sum ./
RUN go mod download

COPY . .

EXPOSE 8080

CMD ["air", "-c", ".air.toml"]
